### ISSUE TITLE
Make New Merge Branch Live

### ISSUE THREAD

**Issue by mcakkerman** [Brown-University-Library/disa_dj_project#27] opened 2020-10-07 15:21 UTC
Merging Patrick code into the existing project in a way everyone can update live. 

If success, Birkin will update with an email, and then any improvements should be made on that branch. There should be no confusion about what branch the three developers should be working on.

**Comment by birkin** [comment] 2020-10-08 03:28
Ok mates... 

- I've merged Patrick's `Tabulator_dev` branch and the production code (in identical dev/master brances) into a new branch named `tabulator_merge`.

- I've made that branch [active on the dev-server](https://dlibwwwcit.services.brown.edu/disa_demo/browse_tabulator/) (VPN required). (Remember you can always check to see the 'live' branch and commit via [this url structure](https://dlibwwwcit.services.brown.edu/disa_demo/version/).)

- @prashleigh & @bentbul: 

    - make improvements to this `tabulator_merge` branch. I'll update the dev-server daily, and at your request, so you can confirm the changes are working there.

    - note that I've removed 'redesign' code from this `tabulator_merge` branch. Hope that's ok Patrick. Because I want this to be live, in production -- I just wanted to focus on getting the tabulator code integrated into the production code. I _do_ want to integrate the redesign-code, too, into production (via this hidden-url method), but let's wait 'til after the community meeting for that.

- Thursday I want to:

    - confirm that no existing functionality has been compromised by my merge (that's laborious and'll take some time) -- I really don't expect any issues.

    - make the `tabulator_merge` branch active in production, too. Once I do that, I'll close this issue, @mcakkerman .

---

**Comment by birkin** [comment] 2020-10-08 23:12
Today I confirmed each of the CRUD (create, read, update, and delete) steps for documents, items, referent-people, and relationships. So I've moved the code into production.

**Closed by birkin** 2020-10-08 23:12 UTC
Labels: birkin-now, patrick-now
